- name: Automatización de servidores
  hosts: all
  become: yes
  tasks:
    - name: Actualizar caché de apt
      apt:
        update_cache: yes

    - name: Instalar apache
      apt:
        name: apache2
        state: present

    - name: Instalar cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear archivo
      file:
        path: /tmp/mi_archivo.txt
        state: touch

    - name: Copiar archivo
      copy:
        src: /ruta/local/archivo.txt
        dest: /tmp/archivo_copiado.txt

    - name: Crear carpetas
      file:
        path: /tmp/mi_carpeta
        state: directory

    - name: Iniciar el servicio apache
      service:
        name: apache2
        state: started

    - name: Agregar un usuario
      user:
        name: nuevo_usuario
        state: present

    - name: Ejecutar un script
      script: /ruta/local/mi_script.sh
